version: "3.9"


services:
  api:
    build: ./backend/
    command: bash docker-entrypoint.sh
    container_name: api
    image: django:app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    env_file:
      backend/.env
    restart: always
    volumes:
      - ./backend/:/app/backend
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      backend/.env
    restart: always
  

   
volumes:
    postgres_data:
